name = "jant"
main = "src/index.ts"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 9019

[vars]
SITE_URL = "https://local.jant.me"

[[d1_databases]]
binding = "DB"
database_name = "jant-db"
database_id = "local"
migrations_dir = "src/db/migrations"

# Uncomment when R2 bucket is created
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "jant-media"
